name: rolemaster_app
description: Aplicación multiplataforma Rolemaster para el Director de Juego.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.2.0
  path_provider: ^2.1.6
  rolemaster_core:
    path: ../../packages/rolemaster_core
  rolemaster_storage_sqlite:
    path: ../../packages/rolemaster_storage_sqlite

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
